/* Only need to add course_id to obtain a list of all students, assessment titles and grades for that course */

SELECT USER_ID, TITLE, SCORE 
  FROM (SELECT GRADEBOOK_MAIN_PK1, PK1, GRADE, COURSE_USERS_PK1
          FROM BB_BB60.GRADEBOOK_GRADE) A, 
       (SELECT PK1, TITLE 
	  FROM BB_BB60.GRADEBOOK_MAIN
	 WHERE CRSMAIN_PK1 = (SELECT PK1 
			        FROM COURSE_MAIN
			       WHERE COURSE_ID = 'COURSE_ID')) B, 
       (SELECT USER_ID, CU.PK1 CU_PK1 
          FROM BB_BB60.USERS, (SELECT PK1, USERS_PK1 
			         FROM BB_BB60.COURSE_USERS) CU
			        WHERE USERS.PK1 = CU.USERS_PK1) C,
       (SELECT GRADEBOOK_GRADE_PK1, SCORE, GRADE GRADEBOOK_GRADE 
          FROM BB_BB60.ATTEMPT) D	 
 WHERE A.GRADEBOOK_MAIN_PK1 = B.PK1
   AND A.COURSE_USERS_PK1 = C.CU_PK1
   AND A.PK1 = D.GRADEBOOK_GRADE_PK1