SELECT COUNT(*) 
  FROM BB_BB60.TASKS 
 WHERE CRSMAIN_PK1 IN 
      (SELECT CRSMAIN_PK1 
         FROM BB_BB60.COURSE_USERS 
        WHERE USERS_PK1 IN
             (SELECT PK1 
                FROM BB_BB60.USERS 
               WHERE USER_ID ='dbrown')) 
   AND TO_DATE(DUEDATE,'DD/MM/YYYY') >= TO_DATE(SYSDATE,'DD/MM/YYYY') 
   AND TO_DATE(DUEDATE,'DD/MM/YYYY') <= TO_DATE((SYSDATE+7),'DD/MM/YYYY')